version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=22043006
      - POSTGRES_USER=postgres
      - POSTGRES_DB=keycloak_db
      - POSTGRES_HOST_AUTH_METHOD=md5
      - PGDATA=/var/lib/postgresql/data
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    command: start --https-certificate-file=/etc/x509/https/fullchain.pem --https-certificate-key-file=/etc/x509/https/privkey.pem
    volumes: 
     - /srv/docker/keycloak/data/certs:/etc/x509/https
    environment:
      KC_HOSTNAME_URL: https://rail200-test.space/keycloak
      KC_HOSTNAME_ADMIN_URL: https://rail200-test.space/keycloak
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_PROXY_HEADERS: forwarded
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: rail200
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 22043006
    ports:
      - 8090:8090
      - 8443:8443
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge

volumes:
  pg_data_volume:
